### ISSUE TITLE
Does this package supports subscription ?

### ISSUE THREAD

**Issue by codejsNeo** [tylerbuchea/graphqless#1]
I did not see any use of the subscription within this package. I was wondering whether its possible to use the subscription feature via this package,

BTW, Thanks for the wonderful package. It really eases a lot of burden !

**Comment by tylerbuchea** [comment]
Hey, @codejsNeo thanks for opening this issue! I think it's technically possible right now but I'll add better support for it as well as an example.

So behind the scenes `.get` and `.post` actually alias the same method and either one should work for defining subscriptions as well. But what I'm going to do is add another alias for `.subscribe` and then put an example in the examples folders as well as on the README.

And thanks again it's stuff like this that is easy to overlook that I need help with 🍻

**Comment by codejsNeo** [comment]
Thanks for replying, this package is cool ..Hope to see it grow in the coming days :+1:

**Comment by tylerbuchea** [comment]
So turns out I lied and it wasn't possible to do subscriptions because of the underlying library.

But the good news is I switched over to using apollo-server-express which does support subscriptions. Let me know if everything is working for you and if you'd be so kind you can close out this issue when you're satisfied.

Take note that you now have to import GraphQLess like this `const { GraphQLess } = require('graphqless')`.

Thanks again for opening this issue you rock 🤘

There is a new example in the examples folder called exampleWithSubscription.js you can run it with `npx nodemon examples/exampleWithSubscription.js` but here is the code for reference as well:

```js
const { GraphQLess, ApolloServerExpress } = require('../index.js');
const { PubSub } = ApolloServerExpress;

const app = new GraphQLess();
const pubsub = new PubSub();
const COUNT_UP = 'COUNT_UP';

let count = 0;
setInterval(() => pubsub.publish(COUNT_UP, { count: count++ }), 1000);

app.subscription('/count', {
  subscribe: () => pubsub.asyncIterator(COUNT_UP),
});

app.query('/dummy', (req, res) => {
  res.send('Hello');
});

app.useSchema(`
  type Subscription {
    count: Int
  }
  type Query {
    dummy: String
  }
`);

app.listen(3000, () => {
  console.log('Visit: http://localhost:3000/graphql');
});
```

**Comment by codejsNeo** [comment]
Thank you for looking into the issue and making it work again. You did not lie :) .. We all go through these stuffs sometime, its fine totally.. what matters is that you stood up to it and made it work.. Actually, You rock !! I am closing the issue. Happy coding :+1:
